export default {
	windowEl: window,
	documentEl: document,
	htmlEl: document.documentElement,
	bodyEl: document.body,
	featuresLinks: document.querySelectorAll(".features__link"),
	featuresImages: document.querySelectorAll(".features__image"),
	clients: document.querySelectorAll(".clients__image"),
	btnBackward: document.getElementById("btnBackward"),
	btnForward: document.getElementById("btnForward"),
	clients: document.querySelectorAll(".clients__image"),
	popup: document.getElementById("popup"),
	popupTrigger: document.getElementById("popupTrigger"),
	popupClose: document.getElementById("popupClose"),
};
